name: Release

on:
  push:
    tags:
      - 'v*'  # å½“æŽ¨é€æ ‡ç­¾æ—¶è§¦å‘ï¼Œå¦‚ v1.0.0
  workflow_dispatch:  # å…è®¸æ‰‹åŠ¨è§¦å‘
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          gcc \
          g++ \
          make \
          python3-dev \
          python3-pip \
          libpython3-dev \
          pkg-config \
          tar \
          gzip
        python -m pip install --upgrade pip
        pip install numpy scipy
        
    - name: Build release version
      run: |
        ./manager.sh build
        
    - name: Create delivery package
      run: |
        # å¦‚æžœæœ‰deliveryå‘½ä»¤ï¼Œä½¿ç”¨å®ƒ
        if grep -q "delivery" manager.sh; then
          ./manager.sh delivery
        else
          # æ‰‹åŠ¨åˆ›å»ºå‘å¸ƒåŒ…
          mkdir -p release
          cp -r bin lib include examples docs README.md release/
          tar -czf BellhopPropagationModel-release.tar.gz -C release .
        fi
        
    - name: List release files
      run: |
        echo "=== Release files ==="
        find . -name "*.tar.gz" -o -name "*Release*" -o -name "*Delivery*" | head -10
        ls -la *.tar.gz || echo "No tar.gz files found"
        
    - name: Get release version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        
        # åˆ›å»ºå‘å¸ƒè¯´æ˜Ž
        cat > release_notes.md << 'EOF'
        ## BellhopPropagationModel Release ${{ steps.get_version.outputs.version }}
        
        ### ðŸ“¦ åŒ…å«å†…å®¹
        - ðŸ”§ ç¼–è¯‘åŽçš„å¯æ‰§è¡Œæ–‡ä»¶
        - ðŸ“š åŠ¨æ€åº“æ–‡ä»¶  
        - ðŸ“– å¤´æ–‡ä»¶å’Œæ–‡æ¡£
        - ðŸ”¬ ä½¿ç”¨ç¤ºä¾‹
        
        ### ðŸš€ ä½¿ç”¨æ–¹æ³•
        ```bash
        # è§£åŽ‹å‘å¸ƒåŒ…
        tar -xzf BellhopPropagationModel-*.tar.gz
        
        # è¿è¡Œç¨‹åº
        ./bin/BellhopPropagationModel input.json output.json
        ```
        
        ### ðŸ“‹ ç³»ç»Ÿè¦æ±‚
        - Linux ç³»ç»Ÿ
        - Python 3.9+
        - NumPy, SciPy
        
        ---
        è‡ªåŠ¨æž„å»ºäºŽ: ${{ github.sha }}
        EOF
        
        # åˆ›å»ºå‘å¸ƒ
        gh release create "$VERSION" \
          --title "BellhopPropagationModel $VERSION" \
          --notes-file release_notes.md \
          --target ${{ github.sha }}
          
    - name: Upload release assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        
        # ä¸Šä¼ ä¸»å‘å¸ƒåŒ…
        if [ -f "./BellhopPropagationModel-release.tar.gz" ]; then
          gh release upload "$VERSION" \
            "./BellhopPropagationModel-release.tar.gz#BellhopPropagationModel-$VERSION-linux.tar.gz"
        fi
        
        # ä¸Šä¼ DeliveryåŒ…ï¼ˆå¦‚æžœå­˜åœ¨ï¼‰
        DELIVERY_FILE=$(find . -name "BellhopPropagationModel_*_Delivery*.tar.gz" | head -1)
        if [ -n "$DELIVERY_FILE" ] && [ -f "$DELIVERY_FILE" ]; then
          gh release upload "$VERSION" \
            "$DELIVERY_FILE#BellhopPropagationModel-$VERSION-delivery.tar.gz"
        fi
